In [6]:
# create a list with integers from 1 to 5 called my_list
# multiply each element with the value 3 using either a loop or a list comprehension and save the result under a new variable

In [5]:
# import numpy as np and create a numpy array called my_array out of my_list from the cell before
# multiply each element of my_array with the value of 3

In [4]:
# create a numpy array called x with numbers from 1 to 6 using the arange method
# create a 2x3 matrix X by rehaping the array x
# determine the row- and column-wise average of X

In [70]:
# create an array y out of the last two elements of x from before
# do this in a way such that y gets not changed once you change the last two elements of x
# examine if this works

### Portfolio optimization

The weights for a **minimum variance portfolio** for a set of assets can be determined by:

$$
w_{\text{mvp}} = \frac{\Sigma^{-1} \mathbf{1}}{\mathbf{1}^\top \Sigma^{-1} \mathbf{1}}
$$

- $\Sigma$ is the $n \times n$ covariance matrix  
- $\mathbf{1}$ is a vector of ones with dimension $n$

The code below downloads close prices of three stock market listed companies and determines their discrete returns.

1. Estimate the covariance matrix of the returns.
2. Determine its determinant and evaluate if it is different from zero.
3. If the determinant is different from zero determine the inverse matrix of $\Sigma$.
4. Determine the weights of the minimum variance portfolio.
5. Determine the eigenvalues and eigenvectors of $\Sigma$.
6. Determine the trace of the covariance matrix by using the trace method, find out what the trace operations calculates.
7. Is the trace of the covariance matrix equal to the sum of its eigenvalues?

In [ ]:
import yfinance as yf

tickers = ["AAPL", "MSFT", "WMT"]
close_prices = yf.download(tickers, start = "2023-01-01", end = "2025-04-30")["Close"]
returns = close_prices.pct_change().dropna().values

[*********************100%***********************]  3 of 3 completed


### Solve a linear equation system

Let:

- x = kg of Blend A
- y = kg of Blend B

We now have two equations:
    
1.	Total weight:
$$
x + y = 10
$$
2.	Total cost (price × weight = total price):
$$
10x + 15y = 12 \times 10 = 120
$$
Which gives:
$$
\begin{aligned}
x + y &= 10 \\
10x + 15y &= 120
\end{aligned}
$$

Define the matrix $A$ and the vector $b$ and solve the linear equation system with numpy. Verify the solution by multiplying the matrix $A$ with the solution vector and see if this delivers $b$.

### Calculate the linear regression OLS estimator

For a linear regression model:

$$
Y = \beta_0 + \beta_1 X_1 + ... + \beta_p X_p + \epsilon
$$

the paramters $\beta_0, ..., \beta_p$ can be estimated by the OLS estimator:

$$
\hat{\mathbf{\beta}} = \left( X^T X \right)^{-1} X^T y
$$

which includes matrix operations and matrix inversion. See the data below and try to calculate $\hat{\mathbf{\beta}}$ for yourself. If you want to, you can do this step by step, i.e.:

1. $X^T X$
2. $\left( X^T X \right)^{-1}$
3. $\left( X^T X \right)^{-1} X^T$
4. $\left( X^T X \right)^{-1} X^T y$

In [32]:
import numpy as np
import pandas as pd

# Set seed for reproducibility
np.random.seed(42)

# Generate 10 observations for two continuous independent variables
x1 = np.random.uniform(0, 10, 10)
x2 = np.random.uniform(0, 5, 10)

# True coefficients
beta_0 = 2.0   # intercept
beta_1 = 1.5   # coefficient for x1
beta_2 = -0.7  # coefficient for x2

# Generate y with some random noise
noise = np.random.normal(0, 1, 10)
y = beta_0 + beta_1 * x1 + beta_2 * x2 + noise

# data 
X = np.column_stack((np.ones(len(x1)), x1, x2))

print("Indepenent variables:")
print(X)
print("Dependent variable:")
print(y)

Indepenent variables:
[[1.         3.74540119 0.10292247]
 [1.         9.50714306 4.84954926]
 [1.         7.31993942 4.1622132 ]
 [1.         5.98658484 1.06169555]
 [1.         1.5601864  0.90912484]
 [1.         1.5599452  0.91702255]
 [1.         0.58083612 1.52121121]
 [1.         8.66176146 2.62378216]
 [1.         6.01115012 2.15972509]
 [1.         7.08072578 1.4561457 ]]
Dependent variable:
[ 6.53322493 13.18027745  9.15833581  8.82438667  5.16954099  3.47222572
  1.87393454 11.73124649  8.96053489 11.71270927]
